services:
  mt5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mt5-workbench
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./volumes/config/.wine:/home/abc/.wine
      - ./volumes/data/audio:/home/abc/audio
    environment:
      - DISPLAY=:1
